

set BUILDDIR=.\build\x64
set BULLETSRC=.\src

cmake -S %BULLETSRC% -B %BUILDDIR% -DBUILD_BULLET_ROBOTICS_GUI_EXTRA:BOOL="0" -DBUILD_BULLET2_DEMOS:BOOL="0" -DBUILD_CPU_DEMOS:BOOL="0" -DINSTALL_LIBS:BOOL="1" -DBUILD_BULLET_ROBOTICS_EXTRA:BOOL="0" -DBUILD_OPENGL3_DEMOS:BOOL="0" -DUSE_MSVC_RUNTIME_LIBRARY_DLL:BOOL="1" -DBUILD_UNIT_TESTS:BOOL="0" 

msbuild %BUILDDIR%\BULLET_PHYSICS.sln /p:configuration=Debug
msbuild %BUILDDIR%\BULLET_PHYSICS.sln /p:configuration=Release