@echo off
SETLOCAL ENABLEDELAYEDEXPANSION

set BINDIRECTION= ..\..\bin
set BUILDDIR=.\build\x64
set OGRESRC=.\src

echo Starting Ogre build.
mkdir %BUILDDIR%

:: CMAKE OGRE
cmake -S %OGRESRC% -B %BUILDDIR% -DOGRE_BUILD_COMPONENT_PROPERTY:BOOL="0" -DOGRE_BUILD_COMPONENT_BITES:BOOL="0" -DOGRE_BUILD_PLUGIN_BSP:BOOL="0" -DOGRE_BUILD_PLUGIN_PCZ:BOOL="0" -DOGRE_BUILD_PLUGIN_OCTREE:BOOL="0" -DOGRE_BUILD_COMPONENT_MESHLODGENERATOR:BOOL="0" -DOGRE_BUILD_COMPONENT_OVERLAY_IMGUI:BOOL="0" -DOGRE_BUILD_SAMPLES:BOOL="0" -DOGRE_BUILD_COMPONENT_OVERLAY:BOOL="1" -DOGRE_BUILD_COMPONENT_RTSHADERSYSTEM:BOOL="0" -DOGRE_BUILD_COMPONENT_PYTHON:BOOL="0" -DOGRE_BUILD_COMPONENT_VOLUME:BOOL="0" -DOGRE_BUILD_COMPONENT_TERRAIN:BOOL="0" -DOGRE_BUILD_PLUGIN_DOT_SCENE:BOOL="0" -DOGRE_BUILD_RENDERSYSTEM_D3D9:BOOL="0" -DOGRE_BUILD_RENDERSYSTEM_D3D11:BOOL="0" -DOGRE_BUILD_RENDERSYSTEM_GL3PLUS:BOOL="0" -DOGRE_BUILD_RENDERSYSTEM_GLES2:BOOL="0" -DOGRE_INSTALL_SAMPLES:BOOL="0" -DOGRE_BUILD_PLUGIN_ASSIMP:BOOL="0" 

msbuild %BUILDDIR%\OGRE.sln /p:configuration=Release /p:Platform=x64

set DLLCOPYDIR=%BUILDDIR%\bin\debug
COPY /y !DLLCOPYDIR!\Codec_STBI_d.dll %BINDIRECTION%
COPY /y !DLLCOPYDIR!\OgreMain_d.dll %BINDIRECTION%
COPY /y !DLLCOPYDIR!\zlib.dll %BINDIRECTION%
COPY /y !DLLCOPYDIR!\Plugin_ParticleFX_d.dll %BINDIRECTION%
COPY /y !DLLCOPYDIR!\RenderSystem_GL_d.dll %BINDIRECTION%
COPY /y !DLLCOPYDIR!\OgreOverlay_d.dll %BINDIRECTION%

set DLLCOPYDIR=%BUILDDIR%\bin\release
COPY /y !DLLCOPYDIR!\Codec_STBI.dll %BINDIRECTION%
COPY /y !DLLCOPYDIR!\OgreMain.dll %BINDIRECTION%
COPY /y !DLLCOPYDIR!\OgreXMLConverter.exe %BINDIRECTION%
COPY /y !DLLCOPYDIR!\Plugin_ParticleFX.dll %BINDIRECTION%
COPY /y !DLLCOPYDIR!\RenderSystem_GL.dll %BINDIRECTION%
COPY /y !DLLCOPYDIR!\OgreOverlay.dll %BINDIRECTION%

echo Ogre build finished.