set BINDIRECTION= ..\..\bin
set BUILDDIR=%~dp0build\x64
set OGRESRC=%~dp0src
mkdir %BUILDDIR%
cmake -S %OGRESRC% -B %BUILDDIR%
-DOGRE_BUILD_COMPONENT_BITES:BOOL="0" 
-DOGRE_BUILD_COMPONENT_BULLET:BOOL="0"
-DOGRE_BUILD_COMPONENT_OVERLAY:BOOL="0"
-DOGRE_BUILD_COMPONENT_OVERLAY_IMGUI:BOOL="0"
-DOGRE_BUILD_COMPONENT_PROPERTY:BOOL="0"
-DOGRE_BUILD_COMPONENT_BSP:BOOL="0"
-DOGRE_BUILD_COMPONENT_DOT_SCENE:BOOL="0"
-DOGRE_BUILD_COMPONENT_OCTREE:BOOL="0"
-DOGRE_BUILD_COMPONENT_OVERLAY:BOOL="0"
-DOGRE_BUILD_COMPONENT_PCZ:BOOL="0"
-DOGRE_BUILD_RENDERSYSTEM_TINY:BOOL="0"
-DOGRE_BUILD_RENDERSYSTEM_VULKAN:BOOL="0"
-DOGRE_BUILD_SAMPLES:BOOL="0"

msbuild %BUILDDIR%\OGRE.sln /p:configuration=Debug
msbuild %BUILDDIR%\OGRE.sln /p:configuration=Release
